apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacivida
spec:
  selector:
    matchLabels:
      app: vacivida
  replicas: 1
  template:
    metadata:
      labels:
        app: vacivida
    spec:
      containers:
      - name: vacivida
        image: okteto.dev/vacivida-backend:latest
        ports:
        - containerPort: 5000